package org.g2fx.g2lib.model;

import com.google.common.collect.Streams;

import java.util.*;
import java.util.stream.IntStream;
import java.util.stream.Stream;

import static org.g2fx.g2lib.model.Connector.ConnTypeBandwidth.*;
import static org.g2fx.g2lib.model.Connector.in;
import static org.g2fx.g2lib.model.Connector.out;
import static org.g2fx.g2lib.model.Visual.VisualType;
import static org.g2fx.g2lib.model.Visual.VisualType.*;

public enum ModuleType {
    M_Keyboard
    (1, "Keyboard", 2,
     ModPage.InOut.ix(5), false,
            List.of(),
     List.of(out("Pitch", Control),
             out("Gate", Logic),
             out("Lin", Control),
             out("Release", Control),
             out("Note", Control),
             out("Exp", Control)),
     List.of(),
     List.of()),
    M_4_Out
    (3, "4 outputs", 2,
     ModPage.InOut.ix(1), true,
            List.of(in("In1", Audio),
             in("In2", Audio),
             in("In3", Audio),
             in("In4", Audio)),
     List.of(),
     List.of(ModParam.Dst_2.mk("Destination"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Pad_1.mk("Pad")),
     List.of(),
            meters(namedRange("In", 4))),
    M_2_Out
    (4, "2 outputs", 2,
     ModPage.InOut.ix(0), true,
            List.of(in("InL", Audio),
             in("InR", Audio)),
     List.of(),
     List.of(ModParam.Dst_1.mk("Destination"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Pad_1.mk("Pad")),
     List.of(),
            meters("L","R")),
    M_Invert
    (5, "Logic Inverter", 2,
     ModPage.Logic.ix(1), false,
            List.of(in("In1", LogicDyn),
             in("In2", LogicDyn)),
     List.of(out("Out1", LogicDyn),
             out("Out2", LogicDyn)),
     List.of(),
     List.of(),
            visuals(led("Inv1"),led("Inv2"))), // grouped singles
    M_OscB
    (7, "Osc B", 5,
     ModPage.Osc.ix(1), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("Sync", Audio),
             in("FmMod", Audio),
             in("ShapeMod", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mkd("FreqCoarse",64),
             ModParam.FreqFine.mkd("FreqFine",64),
             ModParam.Kbt_1.mkd("Kbt",1),
             ModParam.Level_100.mkd("PitchMod",0),
             ModParam.FreqMode_3.mkd("FreqMode",0),
             ModParam.Level_100.mkd("FmAmount",0),
             ModParam.PW.mkd("Shape",0),
             ModParam.Level_100.mkd("ShapeMod",0),
             ModParam.OscBWaveform.mkd("Waveform",2),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.FmLinTrk.mkd("FmMode",0)),
     List.of()),
    M_OscShpB
    (8, "Osc Shape B", 4,
     ModPage.Osc.ix(6), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("Sync", Audio),
             in("FmMod", Audio),
             in("ShapeMod", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("FmAmount"),
             ModParam.PW.mk("Shape"),
             ModParam.Level_100.mk("ShapeMod"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.FmLinTrk.mk("FmMode")),
     List.of(ModParam.OscWaveform_3.mk("Waveform"))),
    M_OscC
    (9, "Osc C", 3,
     ModPage.Osc.ix(2), false,
            List.of(in("PitchVar", ControlDyn),
             in("Sync", Audio),
             in("FmMod", Audio),
             in("Pitch", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("FmAmount"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.FmLinTrk.mk("FmMode"),
             ModParam.Level_100.mk("PitchMod")),
     List.of(ModParam.OscWaveform_2.mk("Waveform"))),
    M_Reverb
    (12, "reverb", 3,
     ModPage.FX.ix(7), false,
            List.of(in("InL", Audio),
             in("InR", Audio)),
     List.of(out("OutL", Audio),
             out("OutR", Audio)),
     List.of(ModParam.ReverbTime.mkd("Time",64),
             ModParam.Level_100.mkd("Brightness",64),
             ModParam.Level_100.mkd("DryWet",64),
             ModParam.ActiveMonitor.mkd("Active",1)),
     List.of(ModParam.RoomType.mk("RoomType"))),
    M_OscString
    (13, "Osc String", 3,
     ModPage.Osc.ix(13), false,
            List.of(in("In", Audio),
             in("Pitch", Control),
             in("PitchVar", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("Decay"),
             ModParam.Level_100.mk("Moisture"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Sw8_1
    (15, "Switch 8-1", 4,
     ModPage.Switch.ix(5), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn),
             in("In7", ControlDyn),
             in("In8", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Control", Control)),
     List.of(ModParam.Sw_3.mk("Source")
             .label("In 1","In 2","In 3","In 4","In 5","In 6","In 7","In 8")),
     List.of()),
    M_ValSw1_2
    (17, "Value Switch 1-2", 2,
     ModPage.Switch.ix(11), true,
            List.of(in("Input", ControlDyn),
             in("Ctrl", ControlDyn)),
     List.of(out("OutOn", ControlDyn),
             out("OutOff", ControlDyn)),
     List.of(ModParam.ValSwVal.mk("Val")
             .label("Out 1","Out 2")),
     List.of(),
            led()),
    M_X_Fade
    (18, "Cross Fader", 2,
     ModPage.Mixer.ix(13), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mkd("MixMod",0),
             ModParam.Bipolar_127.mkd("Mix",0x40),
             ModParam.LogLin.mkd("LogLin",0)),
     List.of()),
    M_Mix4_1B
    (19, "Mixer 4-1 B", 2,
     ModPage.Mixer.ix(5), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixLevel.mk("Lev1"),
             ModParam.MixLevel.mk("Lev2"),
             ModParam.MixLevel.mk("Lev3"),
             ModParam.MixLevel.mk("Lev4"),
             ModParam.ExpLin_2.mk("ExpLin")),
     List.of(),
            meter()),
    M_EnvADSR
    (20, "Envelop ADSR", 4,
     ModPage.Env.ix(0), false,
            List.of(in("In", ControlDyn),
             in("Gate", Logic),
             in("AM", Control)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvShape_3.mkd("Shape",0),
             ModParam.EnvTime.mkd("Attack",0),
             ModParam.EnvTime.mkd("Decay",54),
             ModParam.EnvLevel.mkd("Sustain",100),
             ModParam.EnvTime.mkd("Release",14),
             ModParam.PosNegInvBipInv.mkd("OutputType",0),
             ModParam.OffOn.mkd("KB",1),
             ModParam.EnvNR.mkd("NR",0)),
     List.of(),
            led("Gate")),
    M_Mux1_8
    (21, "Multiplexer 1-8", 2,
     ModPage.Switch.ix(14), false,
            List.of(in("In", ControlDyn),
             in("Ctrl", Control)),
     List.of(out("Out1", ControlDyn),
             out("Out2", ControlDyn),
             out("Out3", ControlDyn),
             out("Out4", ControlDyn),
             out("Out5", ControlDyn),
             out("Out6", ControlDyn),
             out("Out7", ControlDyn),
             out("Out8", ControlDyn)),
     List.of(),
     List.of(),
            ledgroup(Visual.LedGroupType.Radio, 8)), // TODO yaml has 7
    M_PartQuant
    (22, "Partial Quantizer", 2,
     ModPage.Note.ix(2), false,
            List.of(in("In", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.PartialRange.mk("Range")),
     List.of()),
    M_ModADSR
    (23, "Envelope Modulation ADSR", 5,
     ModPage.Env.ix(8), false,
            List.of(in("Gate", Logic),
             in("AttackMod", Control),
             in("DecayMod", Control),
             in("SustainMod", Control),
             in("ReleaseMod", Control),
             in("In", ControlDyn),
             in("AM", Control)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvTime.mk("Attack"),
             ModParam.EnvTime.mk("Decay"),
             ModParam.EnvLevel.mk("Sustain"),
             ModParam.EnvTime.mk("Release"),
             ModParam.Level_100.mk("AttackMod"),
             ModParam.Level_100.mk("DecayMod"),
             ModParam.Level_100.mk("SustainMod"),
             ModParam.Level_100.mk("ReleaseMod"),
             ModParam.PosNegInvBipInv.mk("OutputType"),
             ModParam.OffOn.mk("KB")),
     List.of(),
            led("Gate")),
    M_LfoC
    (24, "LFO C", 2,
     ModPage.LFO.ix(2), false,
            List.of(in("Rate", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.LfoRate_3.mk("Rate"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.OutTypeLfo.mk("OutputType"),
             ModParam.LfoRange_3.mk("Range"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(ModParam.LfoWaveform_1.mk("Waveform")),
            led()),
    M_LfoShpA
    (25, "LFO Shape A", 5,
     ModPage.LFO.ix(3), false,
            List.of(in("Rate", Control),
             in("RateVar", Control),
             in("Rst", Control),
             in("ShapeMod", Control),
             in("PhaseMod", Control),
             in("Dir", Control)),
     List.of(out("Out", Control),
             out("Snc", Control)),
     List.of(ModParam.LfoRate_4.mk("Rate"),
             ModParam.LfoRange_4.mk("Range"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.Level_100.mk("RateMod"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.LfoShpAPW.mk("Shape"),
             ModParam.Level_100.mk("PhaseMod"),
             ModParam.Phase.mk("Phase"),
             ModParam.Level_100.mk("ShapeMod"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.OutTypeLfo.mk("OutputType"),
             ModParam.LfoShpA__Waveform.mk("Waveform")),
     List.of(),
            led()),
    M_LfoA
    (26, "LFO A", 3,
     ModPage.LFO.ix(0), false,
            List.of(in("Rate", Control),
             in("RateVar", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.LfoRate_3.mkd("Rate",0x40),
             ModParam.PolyMono.mkd("PolyMono",0),
             ModParam.Kbt_4.mkd("Kbt",0),
             ModParam.Level_100.mkd("RateMod",0),
             ModParam.LfoA_Waveform.mkd("Waveform",0),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.OutTypeLfo.mkd("OutputType",4),
             ModParam.LfoRange_3.mkd("Range",1)),
     List.of(),
            led()),
    M_OscMaster
    (27, "Osc Master", 3,
     ModPage.Osc.ix(16), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.FreqMode_2.mk("FreqMode"),
             ModParam.Level_100.mk("PitchMod")),
     List.of()),
    M_Saturate
    (28, "Saturate", 2,
     ModPage.Shaper.ix(2), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("Amount"),
             ModParam.Level_100.mk("AmountMod"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.SaturateCurve.mk("Curve")),
     List.of()),
    M_MetNoise
    (29, "Metallic Noise Oscillator", 2,
     ModPage.Osc.ix(10), false,
            List.of(in("FreqMod", ControlDyn),
             in("ColorMod", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Level_100.mk("Color"),
             ModParam.Level_100.mk("Freq"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Level_100.mk("FreqMod"),
             ModParam.Level_100.mk("ColorMod")),
     List.of()),
    M_Device
    (30, "Device", 3,
     ModPage.InOut.ix(7), false,
            List.of(),
     List.of(out("Wheel", Control),
             out("AftTouch", Control),
             out("ControlPedal", Control),
             out("SustainPedal", Logic),
             out("PitchStick", Control),
             out("GlobalWheel1", Control),
             out("GlobalWheel2", Control)),
     List.of(),
     List.of()),
    M_Noise
    (31, "Noise", 2,
     ModPage.Osc.ix(9), false,
            List.of(),
     List.of(out("Out", Audio)),
     List.of(ModParam.NoiseColor.mk("Color"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Eq2Band
    (32, "Eq 2 Band", 3,
     ModPage.Filter.ix(12), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.EqdB.mk("LoSlope"),
             ModParam.EqdB.mk("HiSlope"),
             ModParam.Level_100.mk("Level"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.EqLoFreq.mk("LoFreq"),
             ModParam.EqHiFreq.mk("HiFreq")),
     List.of(),
            meter()),
    M_Eq3Band
    (33, "Eq 3 Band", 4,
     ModPage.Filter.ix(13), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.EqdB.mk("LoSlope"),
             ModParam.EqdB.mk("MidGain"),
             ModParam.EqMidFreq.mk("MidFreq"),
             ModParam.EqdB.mk("HiSlope"),
             ModParam.Level_100.mk("Level"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.EqLoFreq.mk("LoFreq"),
             ModParam.EqHiFreq.mk("HiFreq")),
     List.of(),
            meter()),
    M_ShpExp
    (34, "Shape Exp", 2,
     ModPage.Shaper.ix(3), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("Amount"),
             ModParam.Level_100.mk("AmountMod"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.ShpExpCurve.mk("Curve")),
     List.of()),
    M_SwOnOffM
    (36, "Switch On/Off Momentary", 2,
     ModPage.Switch.ix(0), false,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.OffOn.mk("On").label("On")),
     List.of()),
    M_Pulse
    (38, "Pulse", 2,
     ModPage.Logic.ix(4), true,
            List.of(in("In", LogicDyn),
             in("Time", ControlDyn)),
     List.of(out("Out", LogicDyn)),
     List.of(ModParam.LogicTime.mk("Time"),
             ModParam.Level_100.mk("TimeMod"),
             ModParam.LogicRange.mk("Range")),
     List.of(ModParam.PulseMode.mk("Mode")),
            led()),
    M_Mix8_1B
    (40, "Mixer 8-1 B", 4,
     ModPage.Mixer.ix(9), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn),
             in("In7", ControlDyn),
             in("In8", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixLevel.mk("Lev1"),
             ModParam.MixLevel.mk("Lev2"),
             ModParam.MixLevel.mk("Lev3"),
             ModParam.MixLevel.mk("Lev4"),
             ModParam.MixLevel.mk("Lev5"),
             ModParam.MixLevel.mk("Lev6"),
             ModParam.MixLevel.mk("Lev7"),
             ModParam.MixLevel.mk("Lev8"),
             ModParam.ExpLin_2.mk("ExpLin"),
             ModParam.Pad_3.mk("Pad")),
     List.of(),
            meter()),
    M_EnvH
    (41, "Envelope Hold", 2,
     ModPage.Env.ix(1), false,
            List.of(in("Trig", Logic),
             in("AM", Control),
             in("In", ControlDyn)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvTime.mk("Hold"),
             ModParam.PosNegInv.mk("OutputType")),
     List.of(),
            led("Gate")),
    M_Delay
    (42, "Logic Delay", 2,
     ModPage.Logic.ix(5), true,
            List.of(in("In", LogicDyn),
             in("TimeMod", ControlDyn)),
     List.of(out("Out", LogicDyn)),
     List.of(ModParam.LogicTime.mk("Time"),
             ModParam.Level_100.mk("TimeMod"),
             ModParam.LogicRange.mk("Range")),
     List.of(ModParam.LogicDelayMode.mk("Mode")),
            led()),
    M_Constant
    (43, "Constant Value", 2,
     ModPage.Level.ix(0), false,
            List.of(),
     List.of(out("Out", Control)),
     List.of(ModParam.LevBipUni.mkd("Level",64),
             ModParam.BipUni.mkd("BipUni",0)),
     List.of()),
    M_LevMult
    (44, "Level Multiplier", 2,
     ModPage.Level.ix(6), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(),
     List.of()),
    M_FltVoice
    (45, "Filter Voice", 4,
     ModPage.Filter.ix(9), false,
            List.of(in("In", Audio),
             in("VowelMod", Control),
             in("FreqMod", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Vowel.mk("Vowel1"),
             ModParam.Vowel.mk("Vowel2"),
             ModParam.Vowel.mk("Vowel3"),
             ModParam.Level_100.mk("Level"),
             ModParam.Level_100.mk("Vowel"),
             ModParam.Bipolar_127.mk("VowelMod"),
             ModParam.Level_100.mk("Freq"),
             ModParam.Bipolar_127.mk("FreqMod"),
             ModParam.Bipolar_127.mk("Res"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(),
            meter()),
    M_EnvAHD
    (46, "Envelope AHD", 4,
     ModPage.Env.ix(4), false,
            List.of(in("Trig", Logic),
             in("AM", Control),
             in("In", ControlDyn)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvShape_3.mkd("Shape",0),
             ModParam.EnvTime.mkd("Attack",0),
             ModParam.EnvTime.mkd("Hold",32),
             ModParam.EnvNR.mkd("NR",0),
             ModParam.EnvTime.mkd("Decay",14),
             ModParam.PosNegInv.mkd("OutputType",0),
             ModParam.OffOn.mkd("KB",1)),
     List.of(),
            led("Gate")),
    M_Pan
    (47, "Pan", 2,
     ModPage.Mixer.ix(12), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("OutL", ControlDyn),
             out("OutR", ControlDyn)),
     List.of(ModParam.Level_100.mk("PanMod"),
             ModParam.Bipolar_127.mk("Pan"),
             ModParam.LogLin.mk("LogLin")),
     List.of()),
    M_MixStereo
    (48, "Mixer Stereo", 5,
     ModPage.Mixer.ix(11), true,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn)),
     List.of(out("OutL", ControlDyn),
             out("OutR", ControlDyn)),
     List.of(ModParam.Level_100.mk("Lev1"),
             ModParam.Level_100.mk("Lev2"),
             ModParam.Level_100.mk("Lev3"),
             ModParam.Level_100.mk("Lev4"),
             ModParam.Level_100.mk("Lev5"),
             ModParam.Level_100.mk("Lev6"),
             ModParam.Bipolar_127.mk("Pan1"),
             ModParam.Bipolar_127.mk("Pan2"),
             ModParam.Bipolar_127.mk("Pan3"),
             ModParam.Bipolar_127.mk("Pan4"),
             ModParam.Bipolar_127.mk("Pan5"),
             ModParam.Bipolar_127.mk("Pan6"),
             ModParam.Level_100.mk("LevMaster")),
     List.of(),
            meters("L","R")),
    M_FltMulti
    (49, "Filter Multi-mode", 4,
     ModPage.Filter.ix(4), false,
            List.of(in("In", Audio),
             in("PitchVar", ControlDyn),
             in("Pitch", ControlDyn)),
     List.of(out("LP", Audio),
             out("BP", Audio),
             out("HP", Audio)),
     List.of(ModParam.FltFreq.mk("Freq"),
             ModParam.Level_200.mk("PitchMod"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.GcOffOn.mk("GC"),
             ModParam.Res_1.mk("Res"),
             ModParam.FltSlope_1.mk("Slope"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_ConstSwT
    (50, "Constant Switch Toggling", 2,
     ModPage.Level.ix(2), true,
            List.of(),
     List.of(out("Out", Control)),
     List.of(ModParam.LevBipUni.mk("Lev",1),
             ModParam.OffOn.mk("On").label("Switch"),
             ModParam.BipUni.mk("BipUni")),
     List.of()),
    M_FltNord
    (51, "Filter Nord", 5,
     ModPage.Filter.ix(2), false,
            List.of(in("In", Audio),
             in("PitchVar", ControlDyn),
             in("Pitch", ControlDyn),
             in("FMLin", ControlDyn),
             in("Res", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FltFreq.mk("Freq"),
             ModParam.Level_200.mk("PitchMod"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.GcOffOn.mk("GC"),
             ModParam.Res_1.mk("Res"),
             ModParam.FltSlope_2.mk("Slope"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Level_100.mk("FM_Lin"),
             ModParam.LpBpHpBr.mk("FilterType"),
             ModParam.Level_100.mk("ResMod")),
     List.of()),
    M_EnvMulti
    (52, "Envelope Multi", 6,
     ModPage.Env.ix(6), false,
            List.of(in("Gate", Logic),
             in("In", ControlDyn),
             in("AM", Control)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvLevel.mkd("Level1",0x7f),
             ModParam.EnvLevel.mkd("Level2",0x2d),
             ModParam.EnvLevel.mkd("Level3",0x40),
             ModParam.EnvLevel.mkd("Level4",0),
             ModParam.EnvTime.mkd("Time1",0),
             ModParam.EnvTime.mkd("Time2",0x1e),
             ModParam.EnvTime.mkd("Time3",0x1e),
             ModParam.EnvTime.mkd("Time4",0xe),
             ModParam.EnvNR.mkd("NR",0),
             ModParam.SustainMode_2.mkd("SustainMode",2),
             ModParam.PosNegInvBip.mkd("OutputType",0),
             ModParam.OffOn.mkd("KB",1),
             ModParam.EnvShape_3.mkd("Shape",0)),
     List.of(),
            led("Gate")),
    M_S_and_H
    (53, "Sample & Hold", 2,
     ModPage.Switch.ix(16), false,
            List.of(in("In", ControlDyn),
             in("Ctrl", LogicDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(),
     List.of()),
    M_FltStatic
    (54, "Filter Static", 3,
     ModPage.Filter.ix(5), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FltFreq.mk("Freq"),
             ModParam.Res_1.mk("Res"),
             ModParam.LpBpHp.mk("FilterType"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.GcOffOn.mk("GC")),
     List.of()),
    M_EnvD
    (55, "Envelope Decay", 2,
     ModPage.Env.ix(2), false,
            List.of(in("Trig", Logic),
             in("AM", Control),
             in("In", ControlDyn)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvTime.mk("Decay"),
             ModParam.PosNegInv.mk("OutputType")),
     List.of(),
            led("Gate")),
    M_Automate
    (57, "MIDI Control Automate", 2,
     ModPage.MIDI.ix(6), true,
            List.of(in("In", Logic)),
     List.of(out("Out", Logic)),
     List.of(ModParam.MidiData.mk("Ctrl"),
             ModParam.MidiData.mk("Val"),
             ModParam.MidiCh_20.mk("Ch"),
             ModParam.OffOn.mk("Echo")),
     List.of()),
    M_DrumSynth
    (58, "Drum Synthesizer", 8,
     ModPage.Osc.ix(12), false,
            List.of(in("Trig", Logic),
             in("Vel", Control),
             in("Pitch", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.DrumSynthFreq.mkd("Masterfreq",42),
             ModParam.DrumSynthRatio.mkd("SlaveRatio",15),
             ModParam.EnvTime.mkd("MasterDecay",46),
             ModParam.EnvTime.mkd("SlaveDecay",50),
             ModParam.Level_100.mkd("MasterLevel",120),
             ModParam.Level_100.mkd("SlaveLevel",102),
             ModParam.DrumSynthNoiseFlt.mkd("NoiseFltFreq",57),
             ModParam.Level_100.mkd("NoiseFltRes",32),
             ModParam.Level_100.mkd("NoiseFltSweep",39),
             ModParam.EnvTime.mkd("NoiseFltDecay",49),
             ModParam.LpBpHp.mkd("NoiseFltMode",1),
             ModParam.Level_100.mkd("BendAmount",68),
             ModParam.EnvTime.mkd("BendDecay",61),
             ModParam.Level_100.mkd("Click",79),
             ModParam.Level_100.mkd("Noise",115),
             ModParam.ActiveMonitor.mkd("Active",1)),
     List.of(),
            led("Trig")),
    M_CompLev
    (59, "Compare to Level", 2,
     ModPage.Level.ix(10), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", LogicDyn)),
     List.of(ModParam.Bipolar_127.mk("C")),
     List.of()),
    M_Mux8_1X
    (60, "Multiplexer 8-1 with variable X-Fade", 3,
     ModPage.Switch.ix(15), true,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn),
             in("In7", ControlDyn),
             in("In8", ControlDyn),
             in("Ctrl", Control)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("XFade")),
     List.of(),
            ledgroup(Visual.LedGroupType.Radio, 8)),
    M_Clip
    (61, "Clip", 2,
     ModPage.Shaper.ix(0), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("ClipLevMod"),
             ModParam.Level_100.mk("ClipLev"),
             ModParam.ClipShape.mk("Shape"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Overdrive
    (62, "Overdrive", 2,
     ModPage.Shaper.ix(1), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mkd("AmountMod",0),
             ModParam.Level_100.mkd("Amount",0),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.OverdriveType.mkd("Type",0),
             ModParam.ClipShape.mkd("Shape",1)),
     List.of()),
    M_Scratch
    (63, "Scratch", 3,
     ModPage.FX.ix(6), false,
            List.of(in("In", Audio),
             in("Mod", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.ScratchRatio.mk("Ratio"),
             ModParam.Level_100.mk("RatioMod"),
             ModParam.ScratchDelay.mk("Delay"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Gate
    (64, "Gate", 2,
     ModPage.Logic.ix(0), false,
            List.of(in("In1_1", LogicDyn),
             in("In1_2", LogicDyn),
             in("In2_1", LogicDyn),
             in("In2_2", LogicDyn)),
     List.of(out("Out1", LogicDyn),
             out("Out2", LogicDyn)),
     List.of(),
     List.of(ModParam.GateMode.mk("GateMode1"),
             ModParam.GateMode.mk("GateMode2")),
            visuals(led("Gate1"),led("Gate2"))), // grouped singles
    M_Mix2_1B
    (66, "Scratch", 2,
     ModPage.Mixer.ix(3), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixInvert.mk("Inv1"),
             ModParam.MixLevel.mk("Lev1"),
             ModParam.MixInvert.mk("Inv2"),
             ModParam.MixLevel.mk("Lev2"),
             ModParam.ExpLin_2.mk("ExpLin")),
     List.of()),
    M_ClkGen
    (68, "Clock Generator", 4,
     ModPage.LFO.ix(4), true,
            List.of(in("Rst", Logic)),
     List.of(out("1/96", Logic),
             out("1/16", Logic),
             out("ClkActive", Logic),
             out("Sync", Logic)),
     List.of(ModParam.RateBpm.mk("Rate"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.InternalMaster.mk("Source"),
             ModParam.ClkGenBeatSync.mk("BeatSync"),
             ModParam.ClkGenSwing.mk("Swing")),
     List.of()),
    M_ClkDiv
    (69, "Clock Divider", 2,
     ModPage.Logic.ix(3), true,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn)),
     List.of(out("Out", LogicDyn)),
     List.of(ModParam.Range_128.mk("Divider")),
     List.of(ModParam.ClkDivMode.mk("DivMode"))),
    M_EnvFollow
    (71, "Envelope Follower", 2,
     ModPage.Level.ix(8), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", Control)),
     List.of(ModParam.EnvFollowAttack.mk("Attack"),
             ModParam.EnvFollowRelease.mk("Release")),
     List.of()),
    M_NoteScaler
    (72, "Note Scaler", 2,
     ModPage.Note.ix(3), false,
            List.of(in("In", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.NoteRange.mk("Range")),
     List.of()),
    M_WaveWrap
    (74, "Wave Wrapper", 2,
     ModPage.Shaper.ix(4), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("AmountMod"),
             ModParam.Level_100.mk("Amount"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_NoteQuant
    (75, "Note Quantizer", 2,
     ModPage.Note.ix(0), true,
            List.of(in("In", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.NoteRange.mk("Range"),
             ModParam.NoteQuantNotes.mk("Notes")),
     List.of()),
    M_SwOnOffT
    (76, "Switch On/Off Toggle", 2,
     ModPage.Switch.ix(1), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.OffOn.mk("On").label("On")),
     List.of()),
    M_Sw1_8
    (78, "Switch 1-8", 4,
     ModPage.Switch.ix(9), false,
            List.of(in("In", ControlDyn)),
     List.of(out("Out1", ControlDyn),
             out("Out2", ControlDyn),
             out("Out3", ControlDyn),
             out("Out4", ControlDyn),
             out("Out5", ControlDyn),
             out("Out6", ControlDyn),
             out("Out7", ControlDyn),
             out("Out8", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.Sw_3.mk("Sel")
             .label("Out 1","Out 2","Out 3","Out 4","Out 5","Out 6","Out 7","Out 8")),
     List.of()),
    M_Sw4_1
    (79, "Switch 4-1", 3,
     ModPage.Switch.ix(4), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.Sw_2.mk("Sel")
             .label("In 1","In 2","In 3","In 4")),
     List.of()),
    M_LevAmp
    (81, "Level Amplifier", 2,
     ModPage.Level.ix(5), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.LevAmpGain.mk("Gain"),
             ModParam.LinDB.mk("Type")),
     List.of()),
    M_Rect
    (82, "Rectifier", 2,
     ModPage.Shaper.ix(6), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.RectMode.mk("Mode"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_ShpStatic
    (83, "Shape Static", 2,
     ModPage.Shaper.ix(5), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.ShpStaticMode.mk("Mode"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_EnvADR
    (84, "Envelope ADR", 3,
     ModPage.Env.ix(3), false,
            List.of(in("Gate", Logic),
             in("In", ControlDyn),
             in("AM", Control)),
     List.of(out("Env", Control),
             out("Out", ControlDyn),
             out("End", Logic)),
     List.of(ModParam.EnvShape_3.mk("Shape"),
             ModParam.EnvTime.mk("Attack"),
             ModParam.EnvNR.mk("NR"),
             ModParam.EnvTime.mk("Release"),
             ModParam.TrigGate.mk("TG"),
             ModParam.PosNegInv.mk("OutputType"),
             ModParam.OffOn.mk("KB"),
             ModParam.AdAr.mk("DcyRel")),
     List.of(),
            led("Gate")),
    M_WindSw
    (85, "Window Switch", 2,
     ModPage.Switch.ix(12), true,
            List.of(in("In", ControlDyn),
             in("Ctrl", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Gate", LogicDyn)),
     List.of(ModParam.Range_64.mk("ValFrom"),
             ModParam.Range_64.mk("ValTo")),
     List.of(),
            led()),
    M_8Counter
    (86, "8 Counter", 2,
     ModPage.Logic.ix(6), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn)),
     List.of(out("Out1", LogicDyn),
             out("Out2", LogicDyn),
             out("Out3", LogicDyn),
             out("Out4", LogicDyn),
             out("Out5", LogicDyn),
             out("Out6", LogicDyn),
             out("Out7", LogicDyn),
             out("Out8", LogicDyn)),
     List.of(),
     List.of(),
            ledgroup(Visual.LedGroupType.Radio, 8)),
    M_FltLP
    (87, "Filter Lowpass", 2,
     ModPage.Filter.ix(0), false,
            List.of(in("In", Audio),
             in("Pitch", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FltFreq.mk("Freq"),
             ModParam.Level_100.mk("FreqMod"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(ModParam.HpLpSlopeMode.mk("SlopeMode"))),
    M_Sw1_4
    (88, "Switch 1-4", 3,
     ModPage.Switch.ix(8), false,
            List.of(in("In", ControlDyn)),
     List.of(out("Out1", ControlDyn),
             out("Out2", ControlDyn),
             out("Out3", ControlDyn),
             out("Out4", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.Sw_2.mk("Sel")
             .label("Out 1","Out 2","Out 3","Out 4")),
     List.of()),
    M_Flanger
    (89, "Flanger", 3,
     ModPage.FX.ix(2), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FlangerRate.mk("Rate"),
             ModParam.Level_100.mk("Range"),
             ModParam.Level_100.mk("FeedBack"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Sw1_2
    (90, "Switch 1-2", 2,
     ModPage.Switch.ix(7), false,
            List.of(in("In", ControlDyn)),
     List.of(out("Out2", ControlDyn),
             out("Out1", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.Sw_1.mk("Dest")),
     List.of()),
    M_FlipFlop
    (91, "Flip Flop", 2,
     ModPage.Logic.ix(2), false,
            List.of(in("Clk", LogicDyn),
             in("In", LogicDyn),
             in("Rst", LogicDyn)),
     List.of(out("NotQ", LogicDyn),
             out("Q", LogicDyn)),
     List.of(),
     List.of(ModParam.FlipFlopMode.mk("OperationMode")),
            ledgroup(Visual.LedGroupType.Radio, "QB","Q")),
    M_FltClassic
    (92, "Filter Classic", 4,
     ModPage.Filter.ix(3), false,
            List.of(in("In", Audio),
             in("PitchVar", ControlDyn),
             in("Pitch", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FltFreq.mkd("Freq",75),
             ModParam.Level_200.mkd("PitchMod",0),
             ModParam.Kbt_4.mkd("Kbt",0),
             ModParam.Level_100.mkd("Res",0), // TODO Is this different than Res_1?
             ModParam.ClassicSlope.mkd("Slope",2),
             ModParam.ActiveMonitor.mkd("Active",1)),
     List.of()),
    M_StChorus
    (94, "Stereo Chorus", 3,
     ModPage.FX.ix(0), false,
            List.of(in("In", Audio)),
     List.of(out("OutL", Audio),
             out("OutR", Audio)),
     List.of(ModParam.Level_100.mkd("Detune",20),
             ModParam.Level_100.mkd("Amount",127),
             ModParam.ActiveMonitor.mkd("Active",1)),
     List.of()),
    M_OscD
    (96, "Osc D", 2,
     ModPage.Osc.ix(3), false,
            List.of(in("Pitch", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(ModParam.OscWaveform_2.mk("Waveform"))),
    M_OscA
    (97, "Osc A", 3,
     ModPage.Osc.ix(0), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.OscA_Waveform.mk("Waveform"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.FreqMode_3.mk("FreqMode")),
     List.of()),
    M_FreqShift
    (98, "Frequency Shifter", 3,
     ModPage.FX.ix(4), false,
            List.of(in("In", Audio),
             in("Shift", Control)),
     List.of(out("Dn", Audio),
             out("Up", Audio)),
     List.of(ModParam.FreqShiftFreq.mk("FreqShift"),
             ModParam.Level_100.mk("ShiftMod"),
             ModParam.FreqShiftRange.mk("Range"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Sw2_1
    (100, "Switch 2-1", 2,
     ModPage.Switch.ix(3), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.Sw_1.mk("Sel")
             .label("In 1","In 2")),
     List.of()),
    M_FltPhase
    (102, "Filter Phase", 5,
     ModPage.Filter.ix(6), false,
            List.of(in("In", Audio),
             in("PitchVar", ControlDyn),
             in("Spr", Control),
             in("FB", Control),
             in("Pitch", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Level_100.mk("PitchMod"),
             ModParam.Freq_2.mk("Freq"),
             ModParam.Level_100.mk("SpreadMod"),
             ModParam.Bipolar_127.mk("FB"),
             ModParam.FltPhaseNotchCount.mk("NotchCount"),
             ModParam.Level_100.mk("Spread"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Level_100.mk("Level"),
             ModParam.Level_100.mk("FBMod"),
             ModParam.FltPhaseType.mk("Type"),
             ModParam.Kbt_4.mk("Kbt")),
     List.of(),
            meter()),
    M_EqPeak
    (103, "Eq Peak", 4,
     ModPage.Filter.ix(11), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Freq_3.mkd("Freq",60),
             ModParam.EqdB.mkd("Gain",64),
             ModParam.EqPeakBandwidth.mkd("Bandwidth",64),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.Level_100.mkd("Level",127)),
     List.of(),
            meter()),
    M_ValSw2_1
    (105, "Value Switch 2-1", 2,
     ModPage.Switch.ix(10), true,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("Ctrl", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.ValSwVal.mk("Val")),
     List.of(),
            led()),
    M_OscNoise
    (106, "Oscillator Noise", 3,
     ModPage.Osc.ix(8), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("Width", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("Width"),
             ModParam.Level_100.mk("WidthMod"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Vocoder
    (108, "Vocoder", 8,
     ModPage.Filter.ix(10), true,
            List.of(in("Ctrl", Audio),
             in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.VocoderBand.mk("Band1"),
             ModParam.VocoderBand.mk("Band2"),
             ModParam.VocoderBand.mk("Band3"),
             ModParam.VocoderBand.mk("Band4"),
             ModParam.VocoderBand.mk("Band5"),
             ModParam.VocoderBand.mk("Band6"),
             ModParam.VocoderBand.mk("Band7"),
             ModParam.VocoderBand.mk("Band8"),
             ModParam.VocoderBand.mk("Band9"),
             ModParam.VocoderBand.mk("Band10"),
             ModParam.VocoderBand.mk("Band11"),
             ModParam.VocoderBand.mk("Band12"),
             ModParam.VocoderBand.mk("Band13"),
             ModParam.VocoderBand.mk("Band14"),
             ModParam.VocoderBand.mk("Band15"),
             ModParam.VocoderBand.mk("Band16"),
             ModParam.OffOn.mk("Emphasis"),
             ModParam.ActiveMonitor.mk("Monitor")),
     List.of()),
    M_LevAdd
    (112, "Level Add", 2,
     ModPage.Level.ix(3), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.LevBipUni.mk("Level"),
             ModParam.BipUni.mk("BipUni")),
     List.of()),
    M_Fade1_2
    (113, "Fade 1-2", 2,
     ModPage.Mixer.ix(14), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out1", ControlDyn),
             out("Out2", ControlDyn)),
     List.of(ModParam.Fade12Mix.mk("Mix"),
             ModParam.Level_100.mk("MixMod")),
     List.of()),
    M_Fade2_1
    (114, "Fade 2-1", 2,
     ModPage.Mixer.ix(15), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Fade21Mix.mk("Mix"),
             ModParam.Level_100.mk("MixMod")),
     List.of()),
    M_LevScaler
    (115, "Level Scaler", 3,
     ModPage.Note.ix(7), true,
            List.of(in("Note", Control),
             in("In", ControlDyn)),
     List.of(out("Level", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.LevScaledB.mk("L"),
             ModParam.FreqCoarse.mk("BP"),
             ModParam.LevScaledB.mk("R"),
             ModParam.Kbt_1.mk("Kbt")),
     List.of()),
    M_Mix8_1A
    (116, "Mix 8-1 A", 2,
     ModPage.Mixer.ix(8), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn),
             in("In7", ControlDyn),
             in("In8", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Pad_3.mk("Pad")),
     List.of(),
            meter()),
    M_LevMod
    (117, "Level Modulator", 3,
     ModPage.Level.ix(7), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn),
             in("ModDepth", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("ModDepth"),
             ModParam.LevModAmRm.mk("ModType")),
     List.of()),
    M_Digitizer
    (118, "Digitizer", 3,
     ModPage.FX.ix(3), false,
            List.of(in("In", ControlDyn),
             in("Rate", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.DigitizerBits.mk("Bits"),
             ModParam.DigitizerRate.mk("Rate"),
             ModParam.Level_100.mk("RateMod"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_EnvADDSR
    (119, "Envelope ADDSR", 5,
     ModPage.Env.ix(5), false,
            List.of(in("Gate", Logic),
             in("AM", Control),
             in("In", ControlDyn)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.OffOn.mk("KB"),
             ModParam.EnvShape_3.mk("Shape"),
             ModParam.EnvTime.mk("Attack"),
             ModParam.EnvTime.mk("Decay1"),
             ModParam.EnvLevel.mk("Level1"),
             ModParam.EnvTime.mk("Decay2"),
             ModParam.EnvLevel.mk("Level2"),
             ModParam.EnvTime.mk("Release"),
             ModParam.SustainMode_1.mk("SustainMode"),
             ModParam.PosNegInvBipInv.mk("OutputType"),
             ModParam.EnvNR.mk("NR")),
     List.of(),
            led("Gate")),
    M_SeqNote
    (121, "Sequencer Note", 9,
     ModPage.Seq.ix(3), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn),
             in("Loop", LogicDyn),
             in("Park", LogicDyn),
             in("Note", ControlDyn),
             in("Trig", LogicDyn),
             in("RecVal", ControlDyn),
             in("RecEnable", LogicDyn)),
     List.of(out("Link", LogicDyn),
             out("Note", ControlDyn),
             out("Trig", LogicDyn)),
     List.of(ModParam.FreqCoarse.mk("Seq1Step1"),
             ModParam.FreqCoarse.mk("Seq1Step2"),
             ModParam.FreqCoarse.mk("Seq1Step3"),
             ModParam.FreqCoarse.mk("Seq1Step4"),
             ModParam.FreqCoarse.mk("Seq1Step5"),
             ModParam.FreqCoarse.mk("Seq1Step6"),
             ModParam.FreqCoarse.mk("Seq1Step7"),
             ModParam.FreqCoarse.mk("Seq1Step8"),
             ModParam.FreqCoarse.mk("Seq1Step9"),
             ModParam.FreqCoarse.mk("Seq1Step10"),
             ModParam.FreqCoarse.mk("Seq1Step11"),
             ModParam.FreqCoarse.mk("Seq1Step12"),
             ModParam.FreqCoarse.mk("Seq1Step13"),
             ModParam.FreqCoarse.mk("Seq1Step14"),
             ModParam.FreqCoarse.mk("Seq1Step15"),
             ModParam.FreqCoarse.mk("Seq1Step16"),
             ModParam.OffOn.mk("Seq2Step1"),
             ModParam.OffOn.mk("Seq2Step2"),
             ModParam.OffOn.mk("Seq2Step3"),
             ModParam.OffOn.mk("Seq2Step4"),
             ModParam.OffOn.mk("Seq2Step5"),
             ModParam.OffOn.mk("Seq2Step6"),
             ModParam.OffOn.mk("Seq2Step7"),
             ModParam.OffOn.mk("Seq2Step8"),
             ModParam.OffOn.mk("Seq2Step9"),
             ModParam.OffOn.mk("Seq2Step10"),
             ModParam.OffOn.mk("Seq2Step11"),
             ModParam.OffOn.mk("Seq2Step12"),
             ModParam.OffOn.mk("Seq2Step13"),
             ModParam.OffOn.mk("Seq2Step14"),
             ModParam.OffOn.mk("Seq2Step15"),
             ModParam.OffOn.mk("Seq2Step16"),
             ModParam.LoopOnce.mk("Loop"),
             ModParam.SeqLen.mk("Length"),
             ModParam.TrigGate.mk("TG"),
             ModParam.OffOn.mk("Clr_Or_Rnd"),
             ModParam.OffOn.mk("Rnd_Or_Clr")),
     List.of(),
            visuals(ledgroup(Visual.LedGroupType.Radio, 16),led("Link"))),
    M_Mix4_1C
    (123, "Mixer 4-1 C", 4,
     ModPage.Mixer.ix(6), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixLevel.mkd("Lev1",4,100),
             ModParam.MixLevel.mkd("Lev2",5,100),
             ModParam.MixLevel.mkd("Lev3",6,100),
             ModParam.MixLevel.mkd("Lev4",7,100),
             ModParam.OffOn.mkd("On1",1).label("Ch 1"),
             ModParam.OffOn.mkd("On2",1).label("Ch 2"),
             ModParam.OffOn.mkd("On3",1).label("Ch 3"),
             ModParam.OffOn.mkd("On4",1).label("Ch 4"),
             ModParam.Pad_2.mkd("Pad",0),
             ModParam.ExpLin_2.mkd("ExpLin",0)),
     List.of(),
            meter()),
    M_Mux8_1
    (124, "Multiplexer 8-1", 2,
     ModPage.Switch.ix(13), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn),
             in("In7", ControlDyn),
             in("In8", ControlDyn),
             in("Ctrl", Control)),
     List.of(out("Out", ControlDyn)),
     List.of(),
     List.of(),
            ledgroup(Visual.LedGroupType.Radio, 8)),
    M_WahWah
    (125, "Wah-Wah", 2,
     ModPage.Filter.ix(8), false,
            List.of(in("In", Audio),
             in("Sweep", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Level_100.mk("SweepMod"),
             ModParam.Level_100.mk("Sweep"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Name
    (126, "Name Bar", 1,
     ModPage.InOut.ix(10), false,
            List.of(),
     List.of(),
     List.of(),
     List.of()),
    M_Fx_In
    (127, "Fx Input", 2,
     ModPage.InOut.ix(4), true,
            List.of(),
     List.of(out("OutL", Audio),
             out("OutR", Audio)),
     List.of(ModParam.Source_1.mk("Source"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Pad_4.mk("Pad")),
     List.of(),
            meters("L","R")),
    M_MinMax
    (128, "Min/Max Compare", 2,
     ModPage.Level.ix(12), false,
            List.of(in("A", ControlDyn),
             in("B", ControlDyn)),
     List.of(out("Min", ControlDyn),
             out("Max", ControlDyn)),
     List.of(),
     List.of()),
    M_BinCounter
    (130, "Binary Counter", 2,
     ModPage.Logic.ix(7), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn)),
     List.of(out("Out001", LogicDyn),
             out("Out002", LogicDyn),
             out("Out004", LogicDyn),
             out("Out008", LogicDyn),
             out("Out016", LogicDyn),
             out("Out032", LogicDyn),
             out("Out064", LogicDyn),
             out("Out128", LogicDyn)),
     List.of(),
     List.of(),
            ledgroup(Visual.LedGroupType.BinCounter, 8)),
    M_ADConv
    (131, "A/D Converter", 2,
     ModPage.Logic.ix(8), false,
            List.of(in("In", ControlDyn)),
     List.of(out("D0", LogicDyn),
             out("D1", LogicDyn),
             out("D2", LogicDyn),
             out("D3", LogicDyn),
             out("D4", LogicDyn),
             out("D5", LogicDyn),
             out("D6", LogicDyn),
             out("D7", LogicDyn)),
     List.of(),
     List.of(),
            ledgroup(Visual.LedGroupType.ADConv, 8)),
    M_DAConv
    (132, "D/A Converter", 2,
     ModPage.Logic.ix(9), false,
            List.of(in("D0", LogicDyn),
             in("D1", LogicDyn),
             in("D2", LogicDyn),
             in("D3", LogicDyn),
             in("D4", LogicDyn),
             in("D5", LogicDyn),
             in("D6", LogicDyn),
             in("D7", LogicDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(),
     List.of()),
    M_FltHP
    (134, "Filter Highpass", 2,
     ModPage.Filter.ix(1), false,
            List.of(in("In", Audio),
             in("Pitch", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FltFreq.mk("Freq"),
             ModParam.Level_100.mk("FreqMod"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(ModParam.HpLpSlopeMode.mk("SlopeMode"))),
    M_T_and_H
    (139, "Track & Hold", 2,
     ModPage.Switch.ix(17), false,
            List.of(in("In", ControlDyn),
             in("Ctrl", LogicDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(),
     List.of()),
    M_Mix4_1S
    (140, "Mixer 4-1 Stereo", 4,
     ModPage.Mixer.ix(7), false,
            List.of(in("In1L", ControlDyn),
             in("In1R", ControlDyn),
             in("In2L", ControlDyn),
             in("In2R", ControlDyn),
             in("In3L", ControlDyn),
             in("In3R", ControlDyn),
             in("In4L", ControlDyn),
             in("In4R", ControlDyn),
             in("ChainL", ControlDyn),
             in("ChainR", ControlDyn)),
     List.of(out("OutL", ControlDyn),
             out("OutR", ControlDyn)),
     List.of(ModParam.MixLevel.mk("Lev1",4),
             ModParam.MixLevel.mk("Lev2",5),
             ModParam.MixLevel.mk("Lev3",6),
             ModParam.MixLevel.mk("Lev4",7),
             ModParam.OffOn.mk("On1").label("Ch 1"),
             ModParam.OffOn.mk("On2").label("Ch 2"),
             ModParam.OffOn.mk("On3").label("Ch 3"),
             ModParam.OffOn.mk("On4").label("Ch 4"),
             ModParam.ExpLin_2.mk("ExpLin")),
     List.of(),
            meters("L","R")),
    M_CtrlSend
    (141, "MIDI Control Send", 2,
     ModPage.MIDI.ix(0), true,
            List.of(in("Send", Logic),
             in("Value", Control)),
     List.of(out("Send", Logic)),
     List.of(ModParam.MidiData.mk("Ctrl"),
             ModParam.MidiData.mk("Val"),
             ModParam.MidiCh_20.mk("Ch")),
     List.of()),
    M_PCSend
    (142, "MIDI Program Change Send", 2,
     ModPage.MIDI.ix(1), true,
            List.of(in("Send", Logic),
             in("Program", Control)),
     List.of(out("Send", Logic)),
     List.of(ModParam.MidiData.mk("Program"),
             ModParam.MidiCh_16.mk("Ch")),
     List.of()),
    M_NoteSend
    (143, "MIDI Note Send", 2,
     ModPage.MIDI.ix(2), true,
            List.of(in("Gate", Logic),
             in("Vel", Control),
             in("Note", Control)),
     List.of(),
     List.of(ModParam.MidiData.mk("Vel"),
             ModParam.MidiData.mk("Note"),
             ModParam.MidiCh_20.mk("Ch")),
     List.of()),
    M_SeqEvent
    (144, "Seq Event", 5,
     ModPage.Seq.ix(0), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", Logic),
             in("Loop", Logic),
             in("Park", Logic),
             in("Trig1", Logic),
             in("Trig2", Logic)),
     List.of(out("Link", Logic),
             out("Trig1", LogicDyn),
             out("Trig2", LogicDyn)),
     List.of(ModParam.OffOn.mk("Seq1Step1"),//these have correct default
             ModParam.OffOn.mk("Seq1Step2"),
             ModParam.OffOn.mk("Seq1Step3"),
             ModParam.OffOn.mk("Seq1Step4"),
             ModParam.OffOn.mk("Seq1Step5"),
             ModParam.OffOn.mk("Seq1Step6"),
             ModParam.OffOn.mk("Seq1Step7"),
             ModParam.OffOn.mk("Seq1Step8"),
             ModParam.OffOn.mk("Seq1Step9"),
             ModParam.OffOn.mk("Seq1Step10"),
             ModParam.OffOn.mk("Seq1Step11"),
             ModParam.OffOn.mk("Seq1Step12"),
             ModParam.OffOn.mk("Seq1Step13"),
             ModParam.OffOn.mk("Seq1Step14"),
             ModParam.OffOn.mk("Seq1Step15"),
             ModParam.OffOn.mk("Seq1Step16"),
             ModParam.OffOn.mk("Seq2Step1"),
             ModParam.OffOn.mk("Seq2Step2"),
             ModParam.OffOn.mk("Seq2Step3"),
             ModParam.OffOn.mk("Seq2Step4"),
             ModParam.OffOn.mk("Seq2Step5"),
             ModParam.OffOn.mk("Seq2Step6"),
             ModParam.OffOn.mk("Seq2Step7"),
             ModParam.OffOn.mk("Seq2Step8"),
             ModParam.OffOn.mk("Seq2Step9"),
             ModParam.OffOn.mk("Seq2Step10"),
             ModParam.OffOn.mk("Seq2Step11"),
             ModParam.OffOn.mk("Seq2Step12"),
             ModParam.OffOn.mk("Seq2Step13"),
             ModParam.OffOn.mk("Seq2Step14"),
             ModParam.OffOn.mk("Seq2Step15"),
             ModParam.OffOn.mk("Seq2Step16"),
             ModParam.LoopOnce.mkd("Loop",1),
             ModParam.SeqLen.mkd("Length",15),
             ModParam.TrigGate.mk("TG1"),
             ModParam.TrigGate.mk("TG2")),
     List.of(),
            visuals(ledgroup(Visual.LedGroupType.Radio, 16),led("Link"))),
    M_SeqVal
    (145, "Sequencer Values", 8,
     ModPage.Seq.ix(1), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", Logic),
             in("Loop", Logic),
             in("Park", Logic),
             in("Val", ControlDyn),
             in("Trig", Logic)),
     List.of(out("Link", Logic),
             out("Val", ControlDyn),
             out("Trig", LogicDyn)),
     List.of(ModParam.LevBipUni.mk("Seq1Step1"),
             ModParam.LevBipUni.mk("Seq1Step2"),
             ModParam.LevBipUni.mk("Seq1Step3"),
             ModParam.LevBipUni.mk("Seq1Step4"),
             ModParam.LevBipUni.mk("Seq1Step5"),
             ModParam.LevBipUni.mk("Seq1Step6"),
             ModParam.LevBipUni.mk("Seq1Step7"),
             ModParam.LevBipUni.mk("Seq1Step8"),
             ModParam.LevBipUni.mk("Seq1Step9"),
             ModParam.LevBipUni.mk("Seq1Step10"),
             ModParam.LevBipUni.mk("Seq1Step11"),
             ModParam.LevBipUni.mk("Seq1Step12"),
             ModParam.LevBipUni.mk("Seq1Step13"),
             ModParam.LevBipUni.mk("Seq1Step14"),
             ModParam.LevBipUni.mk("Seq1Step15"),
             ModParam.LevBipUni.mk("Seq1Step16"),
             ModParam.OffOn.mk("Seq2Step1"),
             ModParam.OffOn.mk("Seq2Step2"),
             ModParam.OffOn.mk("Seq2Step3"),
             ModParam.OffOn.mk("Seq2Step4"),
             ModParam.OffOn.mk("Seq2Step5"),
             ModParam.OffOn.mk("Seq2Step6"),
             ModParam.OffOn.mk("Seq2Step7"),
             ModParam.OffOn.mk("Seq2Step8"),
             ModParam.OffOn.mk("Seq2Step9"),
             ModParam.OffOn.mk("Seq2Step10"),
             ModParam.OffOn.mk("Seq2Step11"),
             ModParam.OffOn.mk("Seq2Step12"),
             ModParam.OffOn.mk("Seq2Step13"),
             ModParam.OffOn.mk("Seq2Step14"),
             ModParam.OffOn.mk("Seq2Step15"),
             ModParam.OffOn.mk("Seq2Step16"),
             ModParam.LoopOnce.mk("Loop"),
             ModParam.SeqLen.mk("Length"),
             ModParam.BipUni.mk("BipUni"),
             ModParam.TrigGate.mk("TG"),
             ModParam.OffOn.mk("Clr_Or_Rnd"),
             ModParam.OffOn.mk("Rnd_Or_Clr")),
     List.of(),
            visuals(ledgroup(Visual.LedGroupType.Radio, 16),led("Link"))),
    M_SeqLev
    (146, "Sequencer Level", 8,
     ModPage.Seq.ix(2), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn),
             in("Loop", LogicDyn),
             in("Park", LogicDyn),
             in("Val", ControlDyn),
             in("Trig", LogicDyn)),
     List.of(out("Link", LogicDyn),
             out("Val", ControlDyn),
             out("Trig", LogicDyn)),
     List.of(ModParam.LevBipUni.mk("Seq1Step1"),
             ModParam.LevBipUni.mk("Seq1Step2"),
             ModParam.LevBipUni.mk("Seq1Step3"),
             ModParam.LevBipUni.mk("Seq1Step4"),
             ModParam.LevBipUni.mk("Seq1Step5"),
             ModParam.LevBipUni.mk("Seq1Step6"),
             ModParam.LevBipUni.mk("Seq1Step7"),
             ModParam.LevBipUni.mk("Seq1Step8"),
             ModParam.LevBipUni.mk("Seq1Step9"),
             ModParam.LevBipUni.mk("Seq1Step10"),
             ModParam.LevBipUni.mk("Seq1Step11"),
             ModParam.LevBipUni.mk("Seq1Step12"),
             ModParam.LevBipUni.mk("Seq1Step13"),
             ModParam.LevBipUni.mk("Seq1Step14"),
             ModParam.LevBipUni.mk("Seq1Step15"),
             ModParam.LevBipUni.mk("Seq1Step16"),
             ModParam.OffOn.mk("Seq2Step1"),
             ModParam.OffOn.mk("Seq2Step2"),
             ModParam.OffOn.mk("Seq2Step3"),
             ModParam.OffOn.mk("Seq2Step4"),
             ModParam.OffOn.mk("Seq2Step5"),
             ModParam.OffOn.mk("Seq2Step6"),
             ModParam.OffOn.mk("Seq2Step7"),
             ModParam.OffOn.mk("Seq2Step8"),
             ModParam.OffOn.mk("Seq2Step9"),
             ModParam.OffOn.mk("Seq2Step10"),
             ModParam.OffOn.mk("Seq2Step11"),
             ModParam.OffOn.mk("Seq2Step12"),
             ModParam.OffOn.mk("Seq2Step13"),
             ModParam.OffOn.mk("Seq2Step14"),
             ModParam.OffOn.mk("Seq2Step15"),
             ModParam.OffOn.mk("Seq2Step16"),
             ModParam.LoopOnce.mk("Loop"),
             ModParam.SeqLen.mk("Length"),
             ModParam.BipUni.mk("BipUni"),
             ModParam.TrigGate.mk("TG"),
             ModParam.OffOn.mk("Clr_Or_Rnd"),
             ModParam.OffOn.mk("Rnd_Or_Clr")),
     List.of(),
            visuals(ledgroup(Visual.LedGroupType.Radio, 16),led("Link"))),
    M_CtrlRcv
    (147, "MIDI Control Receive", 2,
     ModPage.MIDI.ix(3), true,
            List.of(),
     List.of(out("Rcv", Logic),
             out("Val", Control)),
     List.of(ModParam.MidiData.mk("Ctrl"),
             ModParam.MidiCh_16.mk("Ch")),
     List.of()),
    M_NoteRcv
    (148, "MIDI Note Receive", 2,
     ModPage.MIDI.ix(4), true,
            List.of(),
     List.of(out("Gate", Logic),
             out("Vel", Control),
             out("RelVel", Control)),
     List.of(ModParam.MidiData.mk("Note"),
             ModParam.MidiCh_17.mk("Ch")),
     List.of()),
    M_NoteZone
    (149, "MIDI Note Zone", 3,
     ModPage.MIDI.ix(5), true,
            List.of(),
     List.of(),
     List.of(ModParam.MidiCh_17.mk("RcvCh"),
             ModParam.MidiData.mk("RcvMin"),
             ModParam.MidiData.mk("RcvMax"),
             ModParam.Bipolar_127.mk("SendTrans"),
             ModParam.MidiCh_20.mk("SendCh"),
             ModParam.NoteZoneThru.mk("ThruMode")),
     List.of()),
    M_Compress
    (150, "Compressor", 5,
     ModPage.FX.ix(8), true,
            List.of(in("InL", Audio),
             in("InR", Audio),
             in("SideChain", Audio)),
     List.of(out("OutR", Audio),
             out("OutL", Audio)),
     List.of(ModParam.Threshold_42.mk("Threshold"),
             ModParam.CompressorRatio.mk("Ratio"),
             ModParam.CompressorAttack.mk("Attack"),
             ModParam.CompressorRelease.mk("Release"),
             ModParam.CompressorRefLevel.mk("RefLevel"),
             ModParam.OffOn.mk("SideChain"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(),
            ledgroup(Visual.LedGroupType.Compressor, 10)),
    M_KeyQuant
    (152, "Key Quantizer", 2,
     ModPage.Note.ix(1), false,
            List.of(in("In", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.NoteRange.mk("Range"),
             ModParam.KeyQuantCapture.mk("Capture"),
             ModParam.OffOn.mk("E"),
             ModParam.OffOn.mk("F"),
             ModParam.OffOn.mk("F#"),
             ModParam.OffOn.mk("G"),
             ModParam.OffOn.mk("G#"),
             ModParam.OffOn.mk("A"),
             ModParam.OffOn.mk("A#"),
             ModParam.OffOn.mk("B"),
             ModParam.OffOn.mk("C"),
             ModParam.OffOn.mk("C#"),
             ModParam.OffOn.mk("D"),
             ModParam.OffOn.mk("D#")),
     List.of()),
    M_SeqCtr
    (154, "Sequencer Controlled", 8,
     ModPage.Seq.ix(4), false,
            List.of(in("Ctrl", ControlDyn),
             in("Val", ControlDyn),
             in("Trig", LogicDyn)),
     List.of(out("Val", ControlDyn),
             out("Trig", LogicDyn)),
     List.of(ModParam.LevBipUni.mk("Seq1Step1"),
             ModParam.LevBipUni.mk("Seq1Step2"),
             ModParam.LevBipUni.mk("Seq1Step3"),
             ModParam.LevBipUni.mk("Seq1Step4"),
             ModParam.LevBipUni.mk("Seq1Step5"),
             ModParam.LevBipUni.mk("Seq1Step6"),
             ModParam.LevBipUni.mk("Seq1Step7"),
             ModParam.LevBipUni.mk("Seq1Step8"),
             ModParam.LevBipUni.mk("Seq1Step9"),
             ModParam.LevBipUni.mk("Seq1Step10"),
             ModParam.LevBipUni.mk("Seq1Step11"),
             ModParam.LevBipUni.mk("Seq1Step12"),
             ModParam.LevBipUni.mk("Seq1Step13"),
             ModParam.LevBipUni.mk("Seq1Step14"),
             ModParam.LevBipUni.mk("Seq1Step15"),
             ModParam.LevBipUni.mk("Seq1Step16"),
             ModParam.OffOn.mk("Seq2Step1"),
             ModParam.OffOn.mk("Seq2Step2"),
             ModParam.OffOn.mk("Seq2Step3"),
             ModParam.OffOn.mk("Seq2Step4"),
             ModParam.OffOn.mk("Seq2Step5"),
             ModParam.OffOn.mk("Seq2Step6"),
             ModParam.OffOn.mk("Seq2Step7"),
             ModParam.OffOn.mk("Seq2Step8"),
             ModParam.OffOn.mk("Seq2Step9"),
             ModParam.OffOn.mk("Seq2Step10"),
             ModParam.OffOn.mk("Seq2Step11"),
             ModParam.OffOn.mk("Seq2Step12"),
             ModParam.OffOn.mk("Seq2Step13"),
             ModParam.OffOn.mk("Seq2Step14"),
             ModParam.OffOn.mk("Seq2Step15"),
             ModParam.OffOn.mk("Seq2Step16"),
             ModParam.TrigGate.mk("TG"),
             ModParam.BipUni.mk("BipUni"),
             ModParam.SeqCtrlXFade.mk("XFade"),
             ModParam.OffOn.mk("Clr_Or_Rnd"),
             ModParam.OffOn.mk("Rnd_Or_Clr")),
     List.of(),
            visuals(ledgroup(Visual.LedGroupType.Radio, 16),led("Link"))),
    M_NoteDet
    (156, "Note Detector", 2,
     ModPage.InOut.ix(9), true,
            List.of(),
     List.of(out("Gate", Logic),
             out("Vel", Control),
             out("RelVel", Control)),
     List.of(ModParam.FreqCoarse.mk("Note")),
     List.of(),
            led("Gate")),
    M_LevConv
    (157, "Level Converter", 2,
     ModPage.Level.ix(4), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.PosNegInvBipInv.mkd("OutputType",4),
             ModParam.BipPosNeg.mkd("InputType",0)),
     List.of()),
    M_Glide
    (158, "Glide", 2,
     ModPage.Note.ix(4), false,
            List.of(in("In", ControlDyn),
             in("On", LogicDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.GlideTime.mkd("Time",64),
             ModParam.OffOn.mkd("Glide",1),
             ModParam.LogLin.mkd("Shape",0)),
     List.of()),
    M_CompSig
    (159, "Compare to Signal", 2,
     ModPage.Level.ix(11), false,
            List.of(in("A", ControlDyn),
             in("B", ControlDyn)),
     List.of(out("Out", LogicDyn)),
     List.of(),
     List.of()),
    M_ZeroCnt
    (160, "Zero Crossing Counter", 2,
     ModPage.Note.ix(6), false,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", Control)),
     List.of(),
     List.of()),
    M_MixFader
    (161, "Mixer 8-1 Fader", 9,
     ModPage.Mixer.ix(10), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn),
             in("In5", ControlDyn),
             in("In6", ControlDyn),
             in("In7", ControlDyn),
             in("In8", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixLevel.mkd("Lev1",8,100),
             ModParam.MixLevel.mkd("Lev2",9,100),
             ModParam.MixLevel.mkd("Lev3",10,100),
             ModParam.MixLevel.mkd("Lev4",11,100),
             ModParam.MixLevel.mkd("Lev5",12,100),
             ModParam.MixLevel.mkd("Lev6",13,100),
             ModParam.MixLevel.mkd("Lev7",14,100),
             ModParam.MixLevel.mkd("Lev8",15,100),
             ModParam.OffOn.mkd("On1",1).label("Ch 1"),
             ModParam.OffOn.mkd("On2",1).label("Ch 2"),
             ModParam.OffOn.mkd("On3",1).label("Ch 3"),
             ModParam.OffOn.mkd("On4",1).label("Ch 4"),
             ModParam.OffOn.mkd("On5",1).label("Ch 5"),
             ModParam.OffOn.mkd("On6",1).label("Ch 6"),
             ModParam.OffOn.mkd("On7",1).label("Ch 7"),
             ModParam.OffOn.mkd("On8",1).label("Ch 8"),
             ModParam.ExpLin_2.mkd("ExpLin",0),
             ModParam.Pad_3.mkd("Pad",0)),
     List.of(),
            meter()),
    M_FltComb
    (162, "Filter Comb", 4,
     ModPage.Filter.ix(7), false,
            List.of(in("In", Audio),
             in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("FB", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Freq_1.mk("Freq"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.Bipolar_127.mk("FB"),
             ModParam.Level_100.mk("FBMod"),
             ModParam.CombType.mk("Type"),
             ModParam.Level_100.mk("Lev"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(),
            meter()),
    M_OscShpA
    (163, "Osc Shape A", 5,
     ModPage.Osc.ix(5), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("Sync", Audio),
             in("FmMod", Audio),
             in("ShapeMod", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("FmAmount"),
             ModParam.FmLinTrk.mk("FmMode"),
             ModParam.PW.mk("Shape"),
             ModParam.Level_100.mk("ShapeMod"),
             ModParam.OscShpA_Waveform.mk("Waveform"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_OscDual
    (164, "Osc Dual", 5,
     ModPage.Osc.ix(7), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("Sync", Audio),
             in("PW", Audio),
             in("Phase", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("SqrLevel"),
             ModParam.Level_100.mk("PWMod"),
             ModParam.Level_100.mk("SawLevel"),
             ModParam.Phase.mk("SawPhase"),
             ModParam.Level_100.mk("SubOctLevel"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.PW.mk("SqrPW"),
             ModParam.Level_100.mk("PhaseMod"),
             ModParam.OffOn.mk("Soft")),
     List.of()),
    M_DXRouter
    (165, "DX Style Router", 6,
     ModPage.Osc.ix(15), false,
            List.of(in("In1", Audio),
             in("In2", Audio),
             in("In3", Audio),
             in("In4", Audio),
             in("In5", Audio),
             in("In6", Audio)),
     List.of(out("Out1", Audio),
             out("Out2", Audio),
             out("Out3", Audio),
             out("Out4", Audio),
             out("Out5", Audio),
             out("Out6", Audio),
             out("Main", Audio)),
     List.of(ModParam.DxAlgorithm.mk("Algorithm"),
             ModParam.DxFeedback.mk("Feedback")),
     List.of()),
    M_PShift
    (167, "Pitch Shifter", 3,
     ModPage.FX.ix(5), false,
            List.of(in("In", Audio),
             in("Pitch", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.PShiftCoarse.mk("ShiftSemi"),
             ModParam.PShiftFine.mk("ShiftFine"),
             ModParam.Level_100.mk("ShiftMod"),
             ModParam.ScratchDelay.mk("Delay"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_ModAHD
    (169, "Envelope Modulation AHD", 5,
     ModPage.Env.ix(7), false,
            List.of(in("Trig", Logic),
             in("AttackMod", Control),
             in("HoldMod", Control),
             in("DecayMod", Control),
             in("In", ControlDyn),
             in("AM", Control)),
     List.of(out("Env", Control),
             out("Out", ControlDyn)),
     List.of(ModParam.EnvTime.mk("Attack"),
             ModParam.EnvTime.mk("Hold"),
             ModParam.EnvTime.mk("Decay"),
             ModParam.Level_100.mk("AttackMod"),
             ModParam.Level_100.mk("HoldMod"),
             ModParam.Level_100.mk("DecayMod"),
             ModParam.PosNegInv.mk("OutputType"),
             ModParam.OffOn.mk("KB")),
     List.of(),
            led("Gate")),
    M_2_In
    (170, "2 inputs", 2,
     ModPage.InOut.ix(2), true,
            List.of(),
     List.of(out("OutL", Audio),
             out("OutR", Audio)),
     List.of(ModParam.Source_2.mk("Source"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Pad_4.mk("Pad")),
     List.of(),
            meters("L","R")),
    M_4_In
    (171, "4 inputs", 2,
     ModPage.InOut.ix(3), true,
            List.of(),
     List.of(out("Out1", Audio),
             out("Out2", Audio),
             out("Out3", Audio),
             out("Out4", Audio)),
     List.of(ModParam.Source_3.mk("Source"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Pad_4.mk("Pad")),
     List.of(),
            meters(namedRange("Out", 4))),
    M_DlySingleA
    (172, "Delay Static", 2,
     ModPage.Delay.ix(0), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.DelayTime_3.mk("Time")),
     List.of(ModParam.DelayRange_3.mk("DelayRange"))),
    M_DlySingleB
    (173, "Delay Single", 2,
     ModPage.Delay.ix(1), false,
            List.of(in("In", Audio),
             in("Time", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.DelayTime_3.mk("Time"),
             ModParam.Level_100.mk("TimeMod")),
     List.of(ModParam.DelayRange_3.mk("DelayRange"))),
    M_DelayDual
    (174, "Delay Dual", 3,
     ModPage.Delay.ix(2), false,
            List.of(in("In", Audio),
             in("Time1", Audio),
             in("Time2", Audio)),
     List.of(out("Out1", Audio),
             out("Out2", Audio)),
     List.of(ModParam.DelayTime_3.mk("Time1"),
             ModParam.Level_100.mk("Time1Mod"),
             ModParam.DelayTime_3.mk("Time2"),
             ModParam.Level_100.mk("Time2Mod")),
     List.of(ModParam.DelayRange_3.mk("DelayRange"))),
    M_DelayQuad
    (175, "Delay Quad", 5,
     ModPage.Delay.ix(3), false,
            List.of(in("In", Audio),
             in("Time1", Audio),
             in("Time2", Audio),
             in("Time3", Audio),
             in("Time4", Audio)),
     List.of(out("OutMain", Audio),
             out("Out1", Audio),
             out("Out2", Audio),
             out("Out3", Audio),
             out("Out4", Audio)),
     List.of(ModParam.DelayTime_3.mk("Time1"),
             ModParam.Level_100.mk("Time1Mod"),
             ModParam.DelayTime_3.mk("Time2"),
             ModParam.Level_100.mk("Time2Mod"),
             ModParam.DelayTime_3.mk("Time3"),
             ModParam.Level_100.mk("Time3Mod"),
             ModParam.DelayTime_3.mk("Time4"),
             ModParam.Level_100.mk("Time4Mod"),
             ModParam.TimeClk.mk("TimeClk")),
     List.of(ModParam.DelayRange_3.mk("DelayRange"))),
    M_DelayA
    (176, "Delay A", 3,
     ModPage.Delay.ix(7), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.DelayTime_2.mkd("Time",64),
             ModParam.Level_100.mkd("FB",64),
             ModParam.Level_100.mkd("Filter",64),
             ModParam.Level_100.mkd("DryWet",64),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.TimeClk.mkd("TimeClk",0)),
     List.of(ModParam.DelayRange_2.mk("DelayRange"))),
    M_DelayB
    (177, "Delay B", 4,
     ModPage.Delay.ix(8), false,
            List.of(in("In", Audio), // 10 <= type "Input"
             in("FBMod", ControlDyn), // 15
             in("DryWetMod", ControlDyn)), // 20
     List.of(out("Out", Audio)), // 11 <= type "Output"
     List.of(ModParam.DelayTime_2.mkd("Time",64), // 6
             ModParam.Level_100.mkd("FB",64), // 7
             ModParam.Level_100.mkd("LP",127), // 19
             ModParam.Level_100.mkd("DryWet",64), // 8
             ModParam.TimeClk.mkd("TimeClk",0), // 29
             ModParam.Level_100.mkd("FBMod",0), // 16
             ModParam.Level_100.mkd("DryWetMod",0), // 6
             ModParam.ActiveMonitor.mkd("Active",1), // 9
             ModParam.Level_100.mkd("HP",0)), // 5
     List.of(ModParam.DelayRange_2.mk("DelayRange"))), // 1 <= type "PartSelector"
    M_DlyClock
    (178, "Delay Clocked", 2,
     ModPage.Delay.ix(6), true,
            List.of(in("In", ControlDyn),
             in("Clk", LogicDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Range_128.mk("Delay")),
     List.of()),
    M_DlyShiftReg
    (179, "Shift Register", 2,
     ModPage.Delay.ix(5), false,
            List.of(in("In", ControlDyn),
             in("Clk", LogicDyn)),
     List.of(out("Out1", ControlDyn),
             out("Out2", ControlDyn),
             out("Out3", ControlDyn),
             out("Out4", ControlDyn),
             out("Out5", ControlDyn),
             out("Out6", ControlDyn),
             out("Out7", ControlDyn),
             out("Out8", ControlDyn)),
     List.of(),
     List.of()),
    M_Operator
    (180, "FM Operator", 12,
     ModPage.Osc.ix(14), false,
            List.of(in("Freq", Control),
             in("FM", Audio),
             in("Gate", Logic),
             in("Note", Control),
             in("AMod", Control),
             in("Vel", Control),
             in("Pitch", Control)),
     List.of(out("Out", Audio)),
     List.of(ModParam.Kbt_1.mkd("Kbt",1),
             ModParam.OffOn.mkd("Sync",0),
             ModParam.RatioFixed.mkd("RatioFixed",0),
             ModParam.OpFreqCoarse.mkd("FreqCoarse",1),
             ModParam.OpFreqFine.mkd("FreqFine",0),
             ModParam.OpFreqDetune.mkd("FreqDetune",7),
             ModParam.OpVel.mkd("Vel",0),
             ModParam.OpRateScale.mkd("RateScale",0),
             ModParam.OpTime.mkd("R1",0x5a),
             ModParam.OpLevel.mkd("L1",0x63),
             ModParam.OpTime.mkd("R2",0x50),
             ModParam.OpLevel.mkd("L2",0x63),
             ModParam.OpTime.mkd("R3",0x46),
             ModParam.OpLevel.mkd("L3",0x63),
             ModParam.OpTime.mkd("R4",0x46),
             ModParam.OpLevel.mkd("L4",0),
             ModParam.OpAmod.mkd("AMod",0),
             ModParam.OpBrPpoint.mkd("BrPoint",0x32),
             ModParam.OpDepthMode.mkd("LDepthMode",0),
             ModParam.OpDepth.mkd("LDepth",0),
             ModParam.OpDepthMode.mkd("RDepthMode",0),
             ModParam.OpDepth.mkd("RDepth",0),
             ModParam.OpLevel.mkd("OutLevel",0x63),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.OffOn.mkd("EnvKB",1)),
     List.of(),
            led("Gate")),
    M_DlyEight
    (181, "Delay 8 Tap", 3,
     ModPage.Delay.ix(4), false,
            List.of(in("In", Audio)),
     List.of(out("Out1", Audio),
             out("Out2", Audio),
             out("Out3", Audio),
             out("Out4", Audio),
             out("Out5", Audio),
             out("Out6", Audio),
             out("Out7", Audio),
             out("Out8", Audio)),
     List.of(ModParam.DelayTime_3.mk("Time")),
     List.of(ModParam.DelayRange_3.mk("DelayRange"))),
    M_DlyStereo
    (182, "Delay Stereo", 5,
     ModPage.Delay.ix(9), false,
            List.of(in("In", Audio)),
     List.of(out("OutL", Audio),
             out("OutR", Audio)),
     List.of(ModParam.DelayTime_1.mkd("TimeLeft",64),
             ModParam.DelayTime_1.mkd("TimeRight",64),
             ModParam.Level_100.mkd("FBLeft",64),
             ModParam.Level_100.mkd("FBRight",64),
             ModParam.Level_100.mkd("XFBLeft",0),
             ModParam.Level_100.mkd("XFBRight",0),
             ModParam.TimeClk.mkd("TimeClk",0),
             ModParam.Level_100.mkd("LP",127),
             ModParam.Level_100.mkd("DryWet",64),
             ModParam.ActiveMonitor.mkd("Active",1),
             ModParam.Level_100.mkd("HP",0)),
     List.of(ModParam.DelayRange_1.mk("DelayRange"))),
    M_OscPM
    (183, "Osc Phase Mod", 3,
     ModPage.Osc.ix(4), false,
            List.of(in("PitchVar", ControlDyn),
             in("Sync", Audio),
             in("PhaseMod", Audio),
             in("Pitch", ControlDyn)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Level_100.mk("PhaseMod"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.Level_100.mk("PitchVar")),
     List.of(ModParam.OscWaveform_1.mk("Waveform"))),
    M_Mix1_1A
    (184, "Mixer 1-1 A", 2,
     ModPage.Mixer.ix(0), false,
            List.of(in("In", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixLevel.mkd("Lev",1,100),
             ModParam.OffOn.mkd("On",1).label("Ch 1"),
             ModParam.ExpLin_2.mkd("ExpLin",0)),
     List.of()),
    M_Mix1_1S
    (185, "Mixer 1-1 Stereo", 2,
     ModPage.Mixer.ix(1), false,
            List.of(in("InL", ControlDyn),
             in("InR", ControlDyn),
             in("LChain", ControlDyn),
             in("RChain", ControlDyn)),
     List.of(out("OutL", ControlDyn),
             out("OutR", ControlDyn)),
     List.of(ModParam.MixLevel.mk("Lev",1),
             ModParam.OffOn.mk("On").label("Ch 2"),
             ModParam.ExpLin_2.mk("ExpLin")),
     List.of()),
    M_Sw1_2M
    (186, "Switch 1-2 Momentary", 2,
     ModPage.Switch.ix(6), false,
            List.of(in("In", ControlDyn)),
     List.of(out("OutOn", ControlDyn),
             out("OutOff", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.OffOn.mk("Sel").label("Switch")),
     List.of()),
    M_Sw2_1M
    (187, "Switch 2-1 Momentary", 2,
     ModPage.Switch.ix(2), false,
            List.of(in("InOff", ControlDyn),
             in("InOn", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Ctrl", Control)),
     List.of(ModParam.OffOn.mk("Sel").label("Switch")),
     List.of()),
    M_ConstSwM
    (188, "Constant Switch Momentary", 2,
     ModPage.Level.ix(1), true,
            List.of(),
     List.of(out("Out", Control)),
     List.of(ModParam.LevBipUni.mk("Lev",1),
             ModParam.OffOn.mk("On").label("Switch"),
             ModParam.BipUni.mk("BipUni")),
     List.of()),
    M_NoiseGate
    (189, "Noise Gate", 3,
     ModPage.Level.ix(9), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Out", ControlDyn),
             out("Env", Control)),
     List.of(ModParam.Threshold_127.mk("Threshold"),
             ModParam.NoiseGateAttack.mk("Attack"),
             ModParam.NoiseGateRelease.mk("Release"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(),
            led()),
    M_LfoB
    (190, "LFO B", 4,
     ModPage.LFO.ix(1), false,
            List.of(in("Rate", Control),
             in("RateVar", Control),
             in("Rst", Control),
             in("Phase", Control)),
     List.of(out("Out", Control),
             out("Sync", Control)),
     List.of(ModParam.LfoRate_4.mk("Rate"),
             ModParam.Level_100.mk("RateMod"),
             ModParam.LfoRange_4.mk("Range"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.LfoB_Waveform.mk("Waveform"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.Phase.mk("Phase"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.OutTypeLfo.mk("OutputType"),
             ModParam.Level_100.mk("PhaseMod")),
     List.of(),
            led()),
    M_Phaser
    (192, "Phaser", 2,
     ModPage.FX.ix(1), false,
            List.of(in("In", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.PhaserType.mk("Type"),
             ModParam.PhaserFreq.mk("Freq"),
             ModParam.Level_100.mk("FeedBack"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Mix4_1A
    (193, "Mixer 4-1 A", 2,
     ModPage.Mixer.ix(4), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("In3", ControlDyn),
             in("In4", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(),
     List.of(),
            meter()),
    M_Mix2_1A
    (194, "Mixer 2-1 A", 2,
     ModPage.Mixer.ix(2), false,
            List.of(in("In1", ControlDyn),
             in("In2", ControlDyn),
             in("Chain", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.MixLevel.mkd("Lev1",1,100),
             ModParam.OffOn.mkd("On1",1).label("Ch 1"),
             ModParam.MixLevel.mkd("Lev2",3,100),
             ModParam.OffOn.mkd("On2",1).label("Ch 2"),
             ModParam.ExpLin_2.mkd("ExpLin",0)),
     List.of()),
    M_ModAmt
    (195, "Modulation Amount", 2,
     ModPage.Level.ix(13), false,
            List.of(in("In", ControlDyn),
             in("Mod", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.Level_100.mk("ModDepth"),
             ModParam.OffOn.mk("On").label("On"),
             ModParam.ExpLin_1.mk("ExpLin"),
             ModParam.ModAmtInvert.mk("InvertMode")),
     List.of()),
    M_OscPerc
    (196, "Osc Percussion", 3,
     ModPage.Osc.ix(11), false,
            List.of(in("Pitch", ControlDyn),
             in("PitchVar", ControlDyn),
             in("Trig", Audio)),
     List.of(out("Out", Audio)),
     List.of(ModParam.FreqCoarse.mk("FreqCoarse"),
             ModParam.FreqFine.mk("FreqFine"),
             ModParam.FreqMode_3.mk("FreqMode"),
             ModParam.Kbt_1.mk("Kbt"),
             ModParam.Level_100.mk("PitchMod"),
             ModParam.Level_100.mk("Decay"),
             ModParam.Level_100.mk("Click"),
             ModParam.OffOn.mk("Punch"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_Status
    (197, "Status", 2,
     ModPage.InOut.ix(8), false,
            List.of(),
     List.of(out("PatchActive", Logic),
             out("VarActive", Logic),
             out("VoiceNo", Control)),
     List.of(),
     List.of()),
    M_PitchTrack
    (198, "Pitch Tracker", 2,
     ModPage.Note.ix(5), true,
            List.of(in("In", ControlDyn)),
     List.of(out("Period", LogicDyn),
             out("Gate", LogicDyn),
             out("Pitch", Control)),
     List.of(ModParam.Threshold_127.mk("Threshold")),
     List.of(),
            led("Gate")),
    M_MonoKey
    (199, "Monophonic Keyboard", 2,
     ModPage.InOut.ix(6), true,
            List.of(),
     List.of(out("Pitch", Control),
             out("Gate", Logic),
             out("Vel", Control)),
     List.of(ModParam.MonoKeyMode.mk("Mode")),
     List.of()),
    M_RandomA
    (200, "Random A", 2,
     ModPage.Rnd.ix(0), false,
            List.of(in("Rate", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.LfoRate_3.mk("Rate"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.BipPosNeg.mk("OutputType"),
             ModParam.LfoRange_3.mk("Range"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.RndEdge.mk("Edge"),
             ModParam.RandomAStepProb.mk("StepProb")),
     List.of(),
            led()),
    M_RandomB
    (202, "Random B", 3,
     ModPage.Rnd.ix(1), false,
            List.of(in("Rate", Control),
             in("RateVar", Control)),
     List.of(out("Out", Control)),
     List.of(ModParam.LfoRate_3.mk("Rate"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.Kbt_4.mk("Kbt"),
             ModParam.Level_100.mk("RateMod"),
             ModParam.Level_100.mk("StepProb"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.BipPosNeg.mk("OutputType"),
             ModParam.LfoRange_3.mk("Range"),
             ModParam.RndEdge.mk("Edge")),
     List.of(),
            led()),
    M_RndClkA
    (204, "Random Clock A", 2,
     ModPage.Rnd.ix(2), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn),
             in("Seed", ControlDyn)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.RndProb.mk("StepProb"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.OffOn.mk("Dice"),
             ModParam.BipPosNeg.mk("OutputType"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of()),
    M_RndTrig
    (205, "Random Trig", 2,
     ModPage.Rnd.ix(4), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn),
             in("Seed", ControlDyn),
             in("Prob", ControlDyn)),
     List.of(out("Out", LogicDyn)),
     List.of(ModParam.RndProb.mk("StepProb"),
             ModParam.Level_100.mk("StepProbMod"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.PolyMono.mk("PolyMono")),
     List.of()),
    M_RndClkB
    (206, "Random Clock B", 3,
     ModPage.Rnd.ix(3), false,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn),
             in("Seed", ControlDyn),
             in("Step", Control)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.RndProb.mk("StepProb"),
             ModParam.BipPosNeg.mk("OutputType"),
             ModParam.ActiveMonitor.mk("Active"),
             ModParam.PolyMono.mk("PolyMono"),
             ModParam.Level_100.mk("StepProbMod")),
     List.of(ModParam.Rnd_1.mk("Character"))),
    M_RndPattern
    (208, "Random Pattern", 3,
     ModPage.Rnd.ix(5), true,
            List.of(in("Clk", LogicDyn),
             in("Rst", LogicDyn),
             in("A", Control),
             in("B", Control),
             in("StepProb", Control)),
     List.of(out("Out", ControlDyn)),
     List.of(ModParam.RangeBip_128.mk("PatternA"),
             ModParam.Level_100.mk("PatternB"),
             ModParam.RndProb.mk("StepProb"),
             ModParam.Range_128.mk("LoopCount"),
             ModParam.Level_100.mk("StepProbMod"),
             ModParam.BipPosNeg.mk("OutputType"),
             ModParam.ActiveMonitor.mk("Active")),
     List.of(ModParam.RndStepPulse.mk("Waveform")));



    public final int ix;
    public final int height;
    public final String longName;
    public final ModPageIx modPageIx;
    public final boolean isLed;
    public final List<Connector> inPorts;
    public final List<Connector> outPorts;
    private final List<NamedParam> params;
    public final List<NamedParam> modes;
    public final String shortName;
    private final Map<VisualType,List<Visual>> visuals;

    ModuleType(int ix,
               String longName,
               int height,
               ModPageIx modPageIx,
               boolean isLed,
               List<Connector> inPorts,
               List<Connector> outPorts,
               List<NamedParam> params,
               List<NamedParam> modes) {
        this(ix
        ,longName
        ,height
        ,modPageIx
        ,isLed
        ,inPorts
        ,outPorts
        ,params
        ,modes
        ,Map.of(Led,List.of(),Meter,List.of()));
    }

    ModuleType(int ix,
               String longName,
               int height,
               ModPageIx modPageIx,
               boolean isLed,
               List<Connector> inPorts,
               List<Connector> outPorts,
               List<NamedParam> params,
               List<NamedParam> modes,
               Map<VisualType,List<Visual>> visuals) {
        this.ix = ix;
        this.height = height;
        this.longName = longName;
        this.modPageIx = modPageIx;
        this.isLed = isLed;
        this.inPorts = inPorts;
        this.outPorts = outPorts;
        this.params = params;
        this.modes = modes;
        this.shortName = mkShortName(name());
        this.visuals = validateVisuals(visuals);
        Arrays.stream(VisualType.values()).forEach(t ->
                ModuleType.this.visuals.computeIfAbsent(t,k->List.of()));
    }

    private static HashMap<VisualType, List<Visual>> validateVisuals(Map<VisualType, List<Visual>> visuals) {
        HashMap<VisualType, List<Visual>> m = new HashMap<>();
        Set<List<String>> names = new HashSet<>();
        for (VisualType vt : VisualType.values()) {
            List<Visual> vs = visuals.get(vt);
            if (vs == null) {
                m.put(vt, List.of());
            } else {
                vs.forEach(v -> {

                });
                m.put(vt, Streams.mapWithIndex(vs.stream(),(v,i) -> {
                    if (!names.add(v.names())) {
                        throw new IllegalStateException("Duplicate name for visual: " + v);
                    }
                    return v.setIndex((int)i);
                }).toList());
            }
        }
        return m;
    }


    private static String mkShortName(String name) {
        return name.substring(2).replace('_','-').replace("-and-","&");
    }

    public List<NamedParam> getParams() {
        return params;
    }

    public Map<VisualType, List<Visual>> getVisuals() {
        return visuals;
    }

    public record ModPageIx(ModPage page, Integer ix) implements Comparable<ModPageIx> {

        @Override
        public int compareTo(ModPageIx o) {
            int c = page.compareTo(o.page);
            if (c != 0) { return c; } else { return ix.compareTo(o.ix); }
        }
    }

    public enum ModPage {
        InOut,
        Note,
        Osc,
        LFO,
        Rnd,
        Env,
        Filter,
        FX,
        Delay,
        Shaper,
        Level,
        Mixer,
        Switch,
        Logic,
        Seq,
        MIDI;

        public ModPageIx ix(int i) {
            return new ModPageIx(this,i);
        }
    }

    public static final Map<Integer,ModuleType> BY_ID = mkById();

    private static Map<Integer, ModuleType> mkById() {
        Map<Integer, ModuleType> m = new TreeMap<>();
        for (ModuleType t : ModuleType.values()) {
            m.put(t.ix,t);
        }
        return m;
    }

    public static final Map<ModPage,List<ModuleType>> BY_PAGE = mkByPage();

    private static Map<ModPage, List<ModuleType>> mkByPage() {
        Map<ModPage, List<ModuleType>> m = new TreeMap<>();
        Stream.of(ModuleType.values()).forEach(mt -> {
            m.compute(mt.modPageIx.page(),(mp, l) -> {
                if (l == null) { l = new ArrayList<>(); }
                l.add(mt);
                return l;
            });
        });
        m.values().forEach(l ->
                l.sort(Comparator.comparingInt(mt -> mt.modPageIx.ix)));
        return m;
    }

    public static ModuleType getById(int id) {
        ModuleType m = BY_ID.get(id);
        if (m == null) {
            throw new IllegalArgumentException("Invalid module id: " + id);
        }
        return m;
    }


    private static Map<VisualType, List<Visual>> meter() {
        return meters(VisualType.Meter.name());
    }

    private static Map<VisualType,List<Visual>> meters(String... names) {
        return Map.of(VisualType.Meter, Arrays.stream(names).map(n ->
                new Visual(VisualType.Meter,List.of(n))).toList());
    }

    private static Map<VisualType,List<Visual>> ledgroup(Visual.LedGroupType groupType, int names) {
        return ledgroup(groupType, namedRange("",names));
    }
    private static Map<VisualType,List<Visual>> ledgroup(Visual.LedGroupType groupType, String... names) {
        return Map.of(LedGroup,List.of(new Visual(LedGroup,groupType,List.of(names),0)));
    }

    private static Map<VisualType, List<Visual>> led() {
        return led("On");
    }
    private static Map<VisualType, List<Visual>> led(String name) {
        return Map.of(Led,List.of(new Visual(Led,List.of(name))));
    }

    private static Map<VisualType,List<Visual>> visuals(
            Map<VisualType, List<Visual>> v1s,
            Map<VisualType, List<Visual>> v2s) {
        HashMap<VisualType, List<Visual>> m = new HashMap<>(v1s);
        for (Map.Entry<VisualType, List<Visual>> e : v2s.entrySet()) {
            List<Visual> l = m.get(e.getKey());
            if (l == null) {
                m.put(e.getKey(),e.getValue());
            } else {
                ArrayList<Visual> lm = new ArrayList<>(l);
                lm.addAll(e.getValue());
                m.put(e.getKey(),lm);
            }
        }
        return m;
    }

    private static String[] namedRange(String prefix, int count) {
        return IntStream.range(0, count).boxed().map(i -> prefix + i)
                .toList().toArray(new String[count]);
    }
}
